substitutions:
  _REGION: "us-west2"
  _REPOSITORY: "npm-repository"

steps:
  - name: "node:20"
    entrypoint: npm
    args: ["ci"]

  - name: "node:20"
    entrypoint: npm
    args: ["test"]

  - name: "node:20"
    entrypoint: npm
    args: ["audit", "--audit-level=high"]

  - name: "node:20"
    entrypoint: bash
    args:
      - "-euc"
      - |
        REGISTRY_URL="https://${_REGION}-npm.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/"

        cat > .npmrc <<EOF
        @prom-client:registry=${REGISTRY_URL}
        ${REGISTRY_URL#https:}:_authToken=$(gcloud auth print-access-token)
        always-auth=true
        EOF

        npm publish --access restricted

options:
  logging: CLOUD_LOGGING_ONLY
